---
application:
  name: 'sigle-proxy'
  project: 'sigle-app'
  organization: 'QoveryCommunity'
  dockerfile: Dockerfile
  publicly_accessible: true
routers:
  - name: main
    custom_domains:
      - branch: main
        domain: alias.sigle.io
    routes:
      - application_name: 'sigle-proxy'
        paths:
          - '/'
